/*
Oracle / PLSQL: WITH
the WITH clause is a subquery factoring clause which is used to create a named subquery block. This block acts as a virtual table or an inline view for a SQL statement. It was first introduced in Oracle 9.2. It reduces the overhead of multiple references of a table alias in a query. 
The scope of the WITH clause subquery block is the SELECT query with which is is associated.
*/

--Ex.

WITH t AS (
  SELECT * FROM EDI_ERR ORDER BY SEQ
), t2 AS (
  SELECT 
    t.QSA_DOC, t.QSA_DOC_ITEM, t.QSA_PN, SUM(QST60_INQTY) QST60_INQTY, MAX(QST60_RECTIME) QST60_RECTIME, MAX(QST60_WHCODE) QST60_WHCODE, t.ERROR_CODE
  FROM t
  INNER JOIN 
  QSTMATSN MAT ON 
    t.QSA_DOC = MAT.QST60_INVPO
    AND t.QSA_DOC_ITEM = MAT.QST60_INVPOLINE
    AND t.QSA_PN = MAT.QST60_PARTCD
  GROUP BY t.QSA_DOC, t.QSA_DOC_ITEM, t.QSA_PN, t.ERROR_CODE
), t3 AS (
 SELECT t.QSA_DOC, t.QSA_DOC_ITEM, t.QSA_PN, SUM(QST_QTY) QST_QTY, t.ERROR_CODE FROM t 
 INNER JOIN QSTINVOICE INV ON
    t.QSA_DOC = INV.QST_PONO
    AND t.QSA_DOC_ITEM = INV.QST_PONOLINE
    AND t.QSA_PN = INV.QST_PARTNO
  GROUP BY t.QSA_DOC, t.QSA_DOC_ITEM, t.QSA_PN, t.ERROR_CODE
), t4 AS (
  SELECT t.QSA_DOC, t.QSA_DOC_ITEM, t.QSA_PN, SUM(ERP_RECQTY) ERP_RECQTY, t.ERROR_CODE FROM t
  INNER JOIN SFC_ERP_LOGCSV ERP ON
    t.QSA_DOC = ERP.ERP_CUSPO
    AND t.QSA_DOC_ITEM = ERP.ERP_CUSPOLINE
    AND t.QSA_PN = ERP.ERP_CUSPARTCD
    AND ERP.EXP_TEMPLATE = 'ReceiveRes'
    AND ERP.ERP_FLAG = 'Y'
  GROUP BY t.QSA_DOC, t.QSA_DOC_ITEM, t.QSA_PN, t.ERROR_CODE
), t5 AS (
  SELECT t.QSA_DOC, t.QSA_DOC_ITEM, t.QSA_PN, SUM(ERP_RECQTY) ERP_RECQTY, t.ERROR_CODE FROM t
  INNER JOIN SFC_ERP_LOGCSV ERP ON
    t.QSA_DOC = ERP.ERP_CUSPO
    AND t.QSA_DOC_ITEM = ERP.ERP_CUSPOLINE
    AND t.QSA_PN = ERP.ERP_CUSPARTCD
    AND ERP.EXP_TEMPLATE = 'InspectRes'
    AND ERP.ERP_FLAG = 'Y'
  GROUP BY t.QSA_DOC, t.QSA_DOC_ITEM, t.QSA_PN, t.ERROR_CODE
), t6 AS (
  SELECT 
    t.*, 
    t2.QST60_RECTIME,
    t2.QST60_WHCODE,
    t2.QST60_INQTY MATSN,
    t3.QST_QTY QSI,
    t4.ERP_RECQTY LOGCSV_RECRES,
    t5.ERP_RECQTY LOGCSV_INSRES
  FROM t2 
  INNER JOIN t ON
    t2.QSA_DOC = t.QSA_DOC
    AND t2.QSA_DOC_ITEM = t.QSA_DOC_ITEM
    AND t2.QSA_PN = t.QSA_PN
    AND t2.ERROR_CODE = t.ERROR_CODE
  LEFT JOIN t3 ON
    t3.QSA_DOC = t.QSA_DOC
    AND t3.QSA_DOC_ITEM = t.QSA_DOC_ITEM
    AND t3.QSA_PN = t.QSA_PN
     AND t3.ERROR_CODE = t.ERROR_CODE
  LEFT JOIN t4 ON
    t4.QSA_DOC = t.QSA_DOC
    AND t4.QSA_DOC_ITEM = t.QSA_DOC_ITEM
    AND t4.QSA_PN = t.QSA_PN
    AND t4.ERROR_CODE = t.ERROR_CODE
  LEFT JOIN t5 ON
    t5.QSA_DOC = t.QSA_DOC
    AND t5.QSA_DOC_ITEM = t.QSA_DOC_ITEM
    AND t5.QSA_PN = t.QSA_PN
    AND t5.ERROR_CODE = t.ERROR_CODE
)
SELECT * FROM t6;
